### ISSUE TITLE
Support other Families

### ISSUE THREAD

**Issue by mgiaco** [ximtech/DWTDelay#1]
Why not change  to

#include "main.h"

**Comment by ximtech** [comment]
Hi. The "main.h" is used for constants and macros, when project is generated with STM32CubeMX and clion plugin. Main header can contain a lot of dependencies which is not used in delay and can confuse. Soon I'll change this type of include when other types of MCU's has been tested.

**Comment by ximtech** [comment]
Changed to "main.h"
